export type AooData = {
  codAoo: string;
  codiceFiscaleEnte: string;
  codiceIpa: string;
  codiceUniAoo: string;
  denominazioneAoo: string;
  denominazioneEnte: string;
  id?: string;
  mail1: string;
  origin: string;
  cap: string;
  codiceCatastaleComune: string;
  codiceComuneISTAT: string;
  cognomeResponsabile: string;
  nomeResponsabile: string;
  dataIstituzione: string;
  indirizzo: string;
  mailResponsabile: string;
  telefonoResponsabile: string;
  tipoMail1: string;
};
