import { GeographicTaxonomy } from './GeographicTaxonomies';

export type OnboardingFormData = {
  businessName: string;
  registeredOffice: string;
  digitalAddress: string;
  geographicTaxonomies: Array<GeographicTaxonomy>;
  zipCode?: string;
  taxCode?: string;
  vatNumber?: string;
  sfeTaxCode?: string;
  county?: string;
  country?: string;
  extendedCountry?: string;
  city?: string;
  ivassCode?: string;
  recipientCode?: string;
  publicServices?: boolean;
  commercialRegisterNumber?: string;
  registrationInRegister?: string;
  registerNumber?: string;
  abiCode?: string;
  vatNumberGroup?: boolean;
  dpoAddress?: string;
  dpoPecAddress?: string;
  dopEmailAddress?: string;
  businessRegisterPlace?: string;
  rea?: string;
  shareCapital?: string;
  supportEmail?: string;
  aooName?: string;
  uoName?: string;
  aooUniqueCode?: string;
  uoUniqueCode?: string;
  isForeignInsurance?: boolean;
  hasVatnumber?: boolean;
};
