import { GeographicTaxonomy } from './GeographicTaxonomies';

export type OnboardingFormData = {
  businessName: string;
  registeredOffice: string;
  zipCode: string;
  digitalAddress: string;
  taxCode: string;
  vatNumber: string;
  city?: string;
  province?: string;
  ivassCode?: string;
  recipientCode: string;
  publicServices?: boolean;
  commercialRegisterNumber?: string;
  registrationInRegister?: string;
  registerNumber?: string;
  abiCode?: string;
  vatNumberGroup?: boolean;
  dpoAddress?: string;
  dpoPecAddress?: string;
  dopEmailAddress?: string;
  geographicTaxonomies: Array<GeographicTaxonomy>;
  businessRegisterPlace?: string;
  rea?: string;
  shareCapital?: string;
  supportEmail?: string;
  aooName?: string;
  uoName?: string;
  aooUniqueCode?: string;
  uoUniqueCode?: string;
};
