export type PDNDBusinessResource = {
  businessTaxId: string;
  businessName: string;
  legalNature?: string;
  legalNatureDescription?: string;
  cciaa: string;
  businessStatus?: string;
  vatNumber: string;
  city: string;
  county: string;
  zipCode: string;
  address: string;
  digitalAddress: string;
  atecoCodes: Array<string>;
  legalForm?: string;
  nRea: string;
  disabledStateInstitution?: string;
  descriptionStateInstitution?: string;
  statusCompanyRI?: string;
  statusCompanyRD?: string;
};