export type UoData = {
  codiceFiscaleEnte: string;
  codiceIpa: string;
  codiceUniAoo?: string;
  codiceUniUo?: string;
  codiceUniUoPadre?: string;
  denominazioneEnte: string;
  descrizioneUo: string;
  codiceFiscaleSfe?: string;
  id?: string;
  mail1: string;
  origin: string;
  CAP: string;
  codiceCatastaleComune: string;
  codiceComuneISTAT: string;
  cognomeResponsabile: string;
  dataAggiornamento: string;
  dataIstituzione: string;
  indirizzo: string;
  tipoMail1: string;
};
