name: Deploy CDN

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - '!.github/**'
      - '!.devops/**'
      - '!infra/**'
      - '!.pre-commit-config.yaml'
      - '!.terraform-version'
      - '!CODEOWNERS'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod
      domain:
        type: choice
        description: Domain
        options:
          - ar
          - pnpg

jobs:
  release_and_deploy:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_cdn_vite_frontdoor.yml@main
    name: "Release [${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}]"
    secrets: inherit
    with:
      environment: ${{ (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}
      file_environment: ${{ format('fe_{0}.env', (github.event_name == 'workflow_dispatch' && inputs.env) || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev') }}
      storage_account_name: 'weu${{ github.domain }}checkoutst01'
      profile_name: 'weu-${{ github.domain }}-checkout-afd-01'
      endpoint_name: 'weu-${{ github.domain }}-checkout-fde-01'
      resource_group_name: checkout-fe-rg
      blob_container_name: $web
      base_path: onboarding

  promote_release:
    name: Promote prerelease release
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.env == 'prod' }}
    runs-on: ubuntu-22.04
    needs: [release_and_deploy]
    steps:
      - uses: pagopa/selfcare-commons/github-actions-template/promote-release@main
        with:
          github_path_token: ${{ secrets.GH_PAT_VARIABLES }}
          release_version: ${{ vars.CURRENT_UAT_VERSION }}
